# Generated by Django 3.1.7 on 2021-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesGobierno',
            fields=[
                ('organizacion_politica', models.CharField(default='-', max_length=200, primary_key=True, serialize=False)),
                ('url1', models.CharField(default='-', editable=False, max_length=200)),
                ('url2', models.CharField(default='-', editable=False, max_length=200)),
            ],
            options={
                'db_table': 'planes_gobierno',
            },
        ),
    ]
