# Generated by Django 3.1.7 on 2021-03-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0002_planesgobierno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanesGobierno',
        ),
    ]
